### ISSUE TITLE
O-ring

### ISSUE THREAD

**Issue by j538** [jkitzes/macroeco#106]
Hello, I am doing a project where I apply the economic O-ring theory to sports teams in order to evaluate their performance. Would the O-ring theory contained in this code work for this application, and is it similar to the O-ring theory of economic development?

**Comment by jkitzes** [comment]
Thanks for being in touch - from my understanding, the O-ring theory in economics is quite different, so the algorithms in this package wouldn't help with that analysis.

**Comment by j538** [comment]
Thanks!
