### ISSUE TITLE
Update project for Python 3+

### ISSUE THREAD

**Issue by sgelias** [jkitzes/macroeco#108]
Currently the project was developed under python version < 3. This issue was address to update the project python version to 3+.

**Comment by sgelias** [comment]
Dear colleagues. I've updated the project to use python 3 syntax. But I've not permissions to push my branch (issue/108) because I've not permissions for it. I would like to contribute for the project development. Can you give permissions for publish my updates to develop branch through a pull request?

**Comment by jkitzes** [comment]
@mqwilber I think you've used this most recently and have a Python 3 fork, right? Want to have a review and potential merge? We should probably keep a v2.x version somewhere also since it's already done.

**Comment by jkitzes** [comment]
Actually @mqwilber I'm not using macroeco at this point, but I think you might be? Do you want me to transfer ownership of the repo to you?

**Comment by sgelias** [comment]
Dear @jkitzes, thanks for the rapid answer. Do you think that I could submit my pull request to the @mqwilber repository?

**Comment by jkitzes** [comment]
I think that might make sense since Mark already has a Python 3 version as well, I believe. Closing this issue for this repo.
