### ISSUE TITLE
Name collision: column names in csv and methods of dataframe

### ISSUE THREAD

**Issue by jkitzes** [jkitzes/macroeco#79]
Subsetting tables throws a cryptic error when the name of a column in a data table (such as "plot") is the same as a method of a dataframe (i.e., df.plot) - it appears that pandas does not create the dot-syntax alias for the column in this case. Document this error (perhaps check for it?).

**Comment by mqwilber** [comment]
Fixed by removing dot syntax in 8bac6df.  No we can handle any column names. Added a few unittests to check this as well.
