### ISSUE TITLE
Complete review of docs to clean up any TODOs and broken links

### ISSUE THREAD

**Issue by jkitzes** [jkitzes/macroeco#91]
Also remove Using Macroeco section, as not critical given that reference is present.

**Comment by mqwilber** [comment]
Updated the `tutorial_macroeco.rst`  in commits 3bac540 and 682a6c6. Has examples and figures now.

**Comment by mqwilber** [comment]
Added explanation of MecoDesktop output to getting started.  We might want more output explanation in the other tutorials.

**Comment by mqwilber** [comment]
`o_ring` and `comm_grid` don't have tutorials. @jkitzes, not trying to pass the buck, but I figured you knew these better so I left them for you.

**Comment by jkitzes** [comment]
Not to eliminate the buck entirely (?), but do they need tutorials? I figured if we show a few cases that give the overall framework, we shouldn't need an explicit tutorial for every function - what do you think?

**Comment by mqwilber** [comment]
Sounds fine to me. Closing...
