### ISSUE TITLE
Warning thrown by df indexing in new pandas

### ISSUE THREAD

**Issue by jkitzes** [jkitzes/macroeco#97]
Again in pandas v0.16.2, `nosetests` throws the warning below, not an error, which is raised by pandas when we try to perform a certain type of assignment in `format_data.py` at L137.

```
/media/sf_jkitzes/Projects/macroeco/macroeco/misc/format_data.py:137: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
```

The link is actually instructive - I couldn't see right away how to adjust the code, hopefully won't be too much trouble for you to figure out.

**Comment by mqwilber** [comment]
Interesting info. Did not know that you could call it that way.  Fixed warning in commit 0835fd1
